include:
  - project: 'cidevops/java-cicd-template'
    ref: master
    file: 'templates/common-java-pipeline.yaml'

variables:
  DOCKERFILE_PATH: "src/main/docker/Dockerfile"
  CI_REGISTRY_IMAGE: "riverlake-help-backend"
  APP_NAME: "riverlake-help-backend"
  K8S_BASE_PATH: "src/main/k8s"
  K8S_ENV: "dev"
  K8S_FILE: "deploy.yaml"
  K8S_NAMESPACE: "app-dev"
  
  # 资源配置（增加以减少 HPA 触发）
  MEMORY_REQUEST: "1Gi"
  MEMORY_LIMIT: "2Gi"
  CPU_REQUEST: "1000m"
  CPU_LIMIT: "2000m"
